apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profile_catalog_description:
    catalog: weaveworks-nginx
    version: v0.1.0
    profile_name: bitnami-nginx
