name: Docs

on:
  pull_request: {}

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch latest pctl binary
        run: |
          curl -sL https://api.github.com/repos/weaveworks/pctl/releases/latest 2>/dev/null | \
          jq -r '.assets[] | select(.browser_download_url | contains("linux_amd64")) | .browser_download_url' | \
          xargs curl -sL | sudo tar xvz -C /usr/local/bin && chmod +x /usr/local/bin/pctl && pctl --help
      - name: Docs
        run: |
          PATH=$PATH:$(go env GOPATH)/bin make docs
